CREATE TABLE DEPARTMENTS
(
    ID bigint PRIMARY KEY NOT NULL,
    NAME varchar(100) NOT NULL,
    ADDRESS varchar(150)
);
CREATE TABLE PERSON
(
    ID bigint PRIMARY KEY NOT NULL,
    POSITION_ID bigint,
    FULLNAME varchar(100),
    DEPARTMENT_ID bigint,
    SALARY float(52),
    CONSTRAINT POSITION_ID FOREIGN KEY (POSITION_ID) REFERENCES POSITION (ID),
    CONSTRAINT DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (ID)
);
CREATE TABLE POSITION
(
    ID bigint PRIMARY KEY NOT NULL,
    NAME varchar(100) NOT NULL
)
